### ISSUE TITLE
Document site JS error

### ISSUE THREAD

**Issue by theryansmee** [ngneat/falso#99]
### Is this a regression?

No

### Description

When I navigate to [`Falso text doc page`](https://ngneat.github.io/falso/docs/text/), I get the following `console.error` and `result` section is broken

![image](https://user-images.githubusercontent.com/7142779/150549280-51986eff-3d78-4574-ac78-1bc7301fe739.png)

### Please provide the exception or error you saw

```true
main.a08bde6d.js:2 ReferenceError: randPronoun is not defined
    at source (eval at _e (494.1f7c73d3.js:2:211206), <anonymous>:4:64)
    at 1be78505.bf2d7062.js:1:150306
    at t.Z (494.1f7c73d3.js:2:197701)
    at li (main.a08bde6d.js:2:267030)
    at Wl (main.a08bde6d.js:2:319111)
    at Au (main.a08bde6d.js:2:306384)
    at Ou (main.a08bde6d.js:2:306312)
    at Tu (main.a08bde6d.js:2:306175)
    at yu (main.a08bde6d.js:2:303162)
    at main.a08bde6d.js:2:252949
cl @ main.a08bde6d.js:2
o.componentDidCatch.n.callback @ main.a08bde6d.js:2
ho @ main.a08bde6d.js:2
vl @ main.a08bde6d.js:2
Ru @ main.a08bde6d.js:2
t.unstable_runWithPriority @ main.a08bde6d.js:2
Ha @ main.a08bde6d.js:2
Nu @ main.a08bde6d.js:2
yu @ main.a08bde6d.js:2
(anonymous) @ main.a08bde6d.js:2
t.unstable_runWithPriority @ main.a08bde6d.js:2
Ha @ main.a08bde6d.js:2
Ka @ main.a08bde6d.js:2
Wa @ main.a08bde6d.js:2
ku @ main.a08bde6d.js:2
is @ main.a08bde6d.js:2
t.hydrate @ main.a08bde6d.js:2
(anonymous) @ main.a08bde6d.js:2
Promise.then (async)
9454 @ main.a08bde6d.js:2
c @ runtime~main.8fef3417.js:1
(anonymous) @ main.a08bde6d.js:2
c.O @ runtime~main.8fef3417.js:1
(anonymous) @ main.a08bde6d.js:2
t @ runtime~main.8fef3417.js:1
(anonymous) @ main.a08bde6d.js:2
main.a08bde6d.js:2 ReferenceError: randQuote is not defined
    at source (eval at _e (494.1f7c73d3.js:2:211206), <anonymous>:4:64)
    at 1be78505.bf2d7062.js:1:150306
    at t.Z (494.1f7c73d3.js:2:197701)
    at li (main.a08bde6d.js:2:267030)
    at Wl (main.a08bde6d.js:2:319111)
    at Au (main.a08bde6d.js:2:306384)
    at Ou (main.a08bde6d.js:2:306312)
    at Tu (main.a08bde6d.js:2:306175)
    at yu (main.a08bde6d.js:2:303162)
    at main.a08bde6d.js:2:252949
```

### Do you want to create a pull request?

No

**Comment by theryansmee** [comment]
The following pages also have similar errors:
- date
- entities
- general
